pipeline:
  xenial:
    image: plugins/docker
    repo: gcr.io/kubeadm/ci-xenial-systemd
    context: images
    dockerfile: images/xenial-systemd-base.dkr
    tag:
      - base-${DRONE_BRANCH}-latest
      - base-${DRONE_BRANCH}-${DRONE_COMMIT}
